databases:
  - name: iglesia_casa_de_pan_db
    plan: free
    databaseName: app_db
    user: app_user_db

services:
  - type: web
    plan: free
    name: app
    runtime: docker
    envVars:
      # Database
      - key: DATABASE_URL
      fromDatabase:
        name: app_db
        property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      # Laravel
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_TIMEZONE
        value: America/Guatemala
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # Image specific varialbles
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1
